### ISSUE TITLE
使用android 4.2的sdk出现编译错误

### ISSUE THREAD

**Issue by scola** [xinthink/xinkvpn#19]
你好，
      我第一次尝试学习这个项目
在环境和工具准备时，编译时出现build failed
我使用的是android4.2的sdk，
看编译log是发现
taskdef class com.android.ant.NewSetupTask cannot be found
我在sdk的anttasks.jar里的确没有找到 com.android.ant.NewSetupTask
是不是之前的sdk里有这个包，

我是android新手，请教一下怎么fix这个编译问题，需要使用老的sdk么。

Thanks！
D:\android\xinkvpn>g eclipse --stacktrace

FAILURE: Build failed with an exception.

* Where:
Script 'D:\android\xinkvpn\.plugin\android.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> taskdef class com.android.ant.NewSetupTask cannot be found
 using the classloader AntClassLoader[D:\android\adt-bundle-windows-x86\sdk\tool
s\lib\anttasks.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\common.jar;D:
\android\adt-bundle-windows-x86\sdk\tools\lib\guava-tools.jar;D:\android\adt-bun
dle-windows-x86\sdk\tools\lib\sdklib.jar;D:\android\adt-bundle-windows-x86\sdk\t
ools\lib\layoutlib_api.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\commo
ns-compress-1.0.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\httpclient-4
.1.1.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\httpcore-4.1.jar;D:\and
roid\adt-bundle-windows-x86\sdk\tools\lib\httpmime-4.1.1.jar;D:\android\adt-bund
le-windows-x86\sdk\tools\lib\commons-logging-1.1.1.jar;D:\android\adt-bundle-win
dows-x86\sdk\tools\lib\commons-codec-1.4.jar;D:\android\adt-bundle-windows-x86\s
dk\tools\lib\dvlib.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\manifmerg
er.jar]

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating script.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptR
unnerImpl.run(DefaultScriptRunnerFactory.java:54)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.
apply(DefaultScriptPluginFactory.java:127)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.appl
yScript(DefaultObjectConfigurationAction.java:82)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.acce
ss$000(DefaultObjectConfigurationAction.java:32)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.ru
n(DefaultObjectConfigurationAction.java:54)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.exec
ute(DefaultObjectConfigurationAction.java:114)
        at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject
.java:841)
        at build_5onicsf223e562731hrslan6bg$_run_closure2.doCall(D:\android\xink
vpn\build.gradle:31)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:141)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:90)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractPro
ject.java:861)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractPro
ject.java:866)
        at org.gradle.api.internal.project.AbstractProject.subprojects(AbstractP
roject.java:849)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMeth
od(BeanDynamicObject.java:196)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObj
ect.java:102)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(Composite
DynamicObject.java:99)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:
83)
        at build_5onicsf223e562731hrslan6bg.run(D:\android\xinkvpn\build.gradle:
27)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptR
unnerImpl.run(DefaultScriptRunnerFactory.java:52)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.
apply(DefaultScriptPluginFactory.java:127)
        at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptPro
cessor.java:38)
        at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(Lifecycle
ProjectEvaluator.java:43)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:463)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:75)
        at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectE
valuationConfigurer.java:23)
        at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectE
valuationConfigurer.java:21)
        at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuil
dConfigurer.java:38)
        at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuil
dConfigurer.java:35)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractPro
ject.java:439)
        at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractP
roject.java:434)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil
dConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:139)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:110)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:78)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:38)
        at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execut
e(InProcessGradleLauncherActionExecuter.java:39)
        at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execut
e(InProcessGradleLauncherActionExecuter.java:25)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
        at org.gradle.launcher.cli.ActionAdapter.execute(ActionAdapter.java:30)
        at org.gradle.launcher.cli.ActionAdapter.execute(ActionAdapter.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:200)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:138)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:48)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.Main.main(Main.java:39)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:50)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:32)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:47)
Caused by: : taskdef class com.android.ant.NewSetupTask cannot be found
 using the classloader AntClassLoader[D:\android\adt-bundle-windows-x86\sdk\tool
s\lib\anttasks.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\common.jar;D:
\android\adt-bundle-windows-x86\sdk\tools\lib\guava-tools.jar;D:\android\adt-bun
dle-windows-x86\sdk\tools\lib\sdklib.jar;D:\android\adt-bundle-windows-x86\sdk\t
ools\lib\layoutlib_api.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\commo
ns-compress-1.0.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\httpclient-4
.1.1.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\httpcore-4.1.jar;D:\and
roid\adt-bundle-windows-x86\sdk\tools\lib\httpmime-4.1.1.jar;D:\android\adt-bund
le-windows-x86\sdk\tools\lib\commons-logging-1.1.1.jar;D:\android\adt-bundle-win
dows-x86\sdk\tools\lib\commons-codec-1.4.jar;D:\android\adt-bundle-windows-x86\s
dk\tools\lib\dvlib.jar;D:\android\adt-bundle-windows-x86\sdk\tools\lib\manifmerg
er.jar]
        at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:622)

        at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:239)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(Bas
icAntBuilder.java:71)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(Ba
sicAntBuilder.java:86)
        at org.gradle.api.internal.project.DefaultAntBuilder.super$3$invokeMetho
d(DefaultAntBuilder.groovy)
        at org.gradle.api.internal.project.DefaultAntBuilder.invokeMethod(Defaul
tAntBuilder.groovy:37)
        at com.jvoegele.gradle.plugins.android.AndroidSetup_r17.setup(AndroidSet
up_r17.groovy:48)
        at com.jvoegele.gradle.plugins.android.AndroidSetup$setup.call(Unknown S
ource)
        at com.jvoegele.gradle.plugins.android.AndroidPlugin.androidSetup(Androi
dPlugin.groovy:89)
        at com.jvoegele.gradle.plugins.android.AndroidPlugin.apply(AndroidPlugin
.groovy:77)
        at com.jvoegele.gradle.plugins.android.AndroidPlugin.apply(AndroidPlugin
.groovy)
        at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.provid
ePlugin(DefaultProjectsPluginContainer.java:107)
        at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.addPlu
ginInternal(DefaultProjectsPluginContainer.java:71)
        at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.apply(
DefaultProjectsPluginContainer.java:37)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.appl
yPlugin(DefaultObjectConfigurationAction.java:101)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.acce
ss$200(DefaultObjectConfigurationAction.java:32)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.ru
n(DefaultObjectConfigurationAction.java:72)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.exec
ute(DefaultObjectConfigurationAction.java:114)
        at org.gradle.groovy.scripts.DefaultScript.apply(DefaultScript.java:87)
        at org.gradle.api.Script$apply.callCurrent(Unknown Source)
        at android_1aj0u2h85pe3pklq9aceh4tpgq.run(D:\android\xinkvpn\.plugin\and
roid.gradle:1)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptR
unnerImpl.run(DefaultScriptRunnerFactory.java:52)
        ... 54 more
Caused by: java.lang.ClassNotFoundException: com.android.ant.NewSetupTask
        at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoa
der.java:1365)
        at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:131
5)
        at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:106
8)
        at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:594)

        ... 77 more

BUILD FAILED

Total time: 10.616 secs

D:\android\xinkvpn>g eclipse --stacktrace

**Comment by iammecn** [comment]
请联系我,我们需要编写一个安卓的客户端. 5ufkefu@gmail.com
www.5uf7.com
